# https://jekyllrb.com/docs/configuration/options/
title: Steven Kalt # site.title

# https://jekyllrb.com/docs/collections/
collections_dir: content
collections:
  # implicit: _posts, _drafts
  - recipes
  - reading
  - projects
  
# https://help.github.com/en/articles/configuring-jekyll-plugins
plugins:
  # > Default plugins are enabled by default and cannot be disabled.
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  # > Optional plugins:
  # https://jekyllrb.com/docs/github-pages/
  # > Note that GitHub Pages runs in safe mode and only allows a set of whitelisted plugins.
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  # not enabled:
  # - jekyll-redirect-from
  # - jekyll-avatar
  # - jemoji
  # - jekyll-mentions
  # - jekyll-include-cache

# files __not__ to process or serve
exclude:
  # rb artefacts
  - Gemfile
  - Gemfile.lock
  - vendor  # directory in which I'm caching the results of gem installation

  # js artefacts
  - node_modules
  - package.json
  - yarn-error.log
  - yarn.lock

  # development tooling specific to this project
  - src # for JS-managed files. `src` is the canonical place for them.
  - scripts
  - LICENSE
  - README.md
  - Dockerfile

# Inputs set by GitHub:
## https://help.github.com/en/articles/configuring-jekyll#defaults-you-can-change
encoding: UTF-8
markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
 math_engine: mathjax # <- can't change
 syntax_highlighter: rouge # <- can't change
future: true
jailed: false
gfm_quirks: paragraph_end
## https://help.github.com/en/articles/configuring-jekyll#configuration-settings-you-cannot-change
## including these
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
