baseurl           = '/'
copyright         = '© Steven Kalt; This work is licensed as [CC-BY-NC-SA 4.0]("http://creativecommons.org/licenses/by-sa/4.0/")'
disableKinds      = ['taxonomy', 'term']
enableGitInfo     = true
enableRobotsTXT   = true
languageCode      = 'en-us'
publishDir        = 'public'
removePathAccents = true
title             = 'Steven Kalt'

[outputs]
  home = ['html', 'rss']

[params]
  AuthorName = 'Steven Kalt'
  GitHubUser = 'skalt'

[frontmatter]
  date        = [':filename', 'date', 'publishDate']
  lastmod     = [':git', 'date', 'lastmod', 'publishDate']
  publishDate = ['date', 'publishDate']

[markup]
  [markup.highlight]
    # see https://gohugo.io/getting-started/configuration-markup/#highlight
    noclasses = false
  [markup.tableOfContents]
    endLevel   = 3
    ordered    = false
    startLevel = 2
  [markup.goldmark.renderer]
    unsafe = true

[build]
  noJSConfigInAssets = true

[permalinks]
  posts = '/posts/:year/:month/:day/:slug'

[security.funcs]
  getenv = ['^CI$', '^HUGO_', '^PWD$']
