baseurl = 'https://skalt.github.io/'
title = 'Steven Kalt'
enableGitInfo = true
copyright = '© Steven Kalt; This work is licensed as <a href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-NC-SA 4.0</a>'
languageCode = 'en-us'
enableRobotsTXT = true
[outputs]
  home = ['html', 'rss']
[params]
  AuthorName = 'Steven Kalt'
  GitHubUser = 'skalt'

[frontmatter]
    lastmod = [':git', 'lastmod', 'date', 'publishDate']
    publishDate = ['publishDate', 'date']
    date = [':filename']

[markup]
  [markup.highlight]
    # see https://gohugo.io/getting-started/configuration-markup/#highlight
    noclasses = false

[build]
  noJSConfigInAssets = true

[permalinks]
  posts = '/:year/:month/:day/:slug'
  # TODO: - => _

[security.funcs]
  getenv = ['^HUGO_', '^CI$', '^PWD$']
