version: "3"
services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: ["jekyll", "serve", "--livereload"]
    ports:
      - 4000:4000
      - 35729:35729 # for the livereload.js
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
  js:
    image: node:lts-alpine
    volumes:
      - .:/root
    working_dir: "/root"
    command: ["/root/node_modules/.bin/rollup", "-c", "--watch"]
